spring.application.name=ecommerce_skeleton_backend

server.port=8080

spring.threads.virtual.enabled=true

#spring.docker.compose.file=../docker-compose.yml
spring.datasource.url=jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:ecommerce}
spring.datasource.username=${DB_USER:root}
spring.datasource.password=${DB_PASSWORD:toor}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.defer-datasource-initialization=true
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.yaml


#spring.sql.init.mode=always

management.endpoints.web.exposure.include=health,metrics,info,prometheus
management.endpoint.health.probes.enabled=true
management.health.livenessstate.enabled=true
management.health.readinessstate.enabled=true

spring.docker.compose.enabled=${SPRING_DOCKER_COMPOSE_ENABLED:false}

springdoc.show-actuator=true

logging.level.root=WARN
logging.level.web=WARN
logging.level.sql=INFO

logging.level.com.ecommerce_skeleton_backend.controller=INFO
logging.level.com.ecommerce_skeleton_backend.service=INFO
logging.level.com.ecommerce_skeleton_backend.entity=DEBUG
